#!/bin/bash
if [ ! -e "raw_data" ]; then mkfifo raw_data; fi
python image_generator.py -d &
#ffmpeg2theora raw_data -vcodec mjpeg --inputfps 2 --videobitrate 30 --noaudio -o -| oggfwd localhost 8000 hackme /thesec.ogg 
ffmpeg -y -r 2 -vcodec mjpeg -f image2pipe -i raw_data -vcodec libtheora -f pipe "pipe:" | oggfwd localhost 8000 hackme /thesec.ogg 
